# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreInstaller@0
  inputs:
    version: '3.1.201' # replace this value with the version that you need for your project

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '$(solution)'

# dotnet test --no-build --filter skip!=true
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(solution)'
    arguments: ' --no-build --filter skip!=true'