# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk'
  inputs:
    packageType: sdk
    version: 3.1.201
    
- task: UseDotNet@2
  displayName: 'Use .NET 5 sdk'
  inputs:
    packageType: sdk
    version: 5.0.100-preview.8.20417.9

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: build
    projects: '$(solution)'

# dotnet test --no-build --filter skip!=true
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(solution)'
    arguments: ' --no-build --filter skip!=true'